### ISSUE TITLE
[INTRO] Kevin Lacaille

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs-community/planet-hack-2020#3]
_Hi, my name is:_ Kevin Lacaille (la-k-eye)
_my pronouns are:_he/him/his

------

**What I bring to a hack team (skills, experience, interest, etc):** I am an astrophysicist -> software engineer! I am passionate about image processing and statistical analysis. I primarly develop in `python` and `MATLAB`.

**What kind of project I'd like to work on:** I would love to work on projects related to training neural networks and image processing!

**Comment by guy1ziv2** [comment]
can I interest you in the project I proposed?

**Comment by kevinlacaille** [comment]
Absolutley! I just read [your project pitch](https://github.com/planetlabs-community/planet-hack-2020/issues/64) and I'd love to take part.
