### ISSUE TITLE
[INTRO] Grad Student

### ISSUE THREAD

**Issue by BharatiChaudhury** [planetlabs-community/planet-hack-2020#32]
Hi, my name is: Bharathi
My pronouns are: she,her

What I bring to a hack team (skills, experience, interest, etc): I am a computer science student working in the intersection of machine learning and remote sensing applications of agriculture. I have experience using remote sensing imagery, deep learning, python programming, computer vision.

What kind of project I'd like to work on: I am interested in working with agriculture applications and also would love to contribute to a team with similar or varied interests.

**Comment by guy1ziv2** [comment]
are you interested in working on the project I proposed to map agricultural field boundaries, possibly using deep learning (U-net)?

**Comment by BharatiChaudhury** [comment]
Yes, i am interested. I have some experience on that as well.

**Comment by BharatiChaudhury** [comment]
@guy1ziv2 Yes. Its interesting to me.
