### ISSUE TITLE
BackyardCreators

### ISSUE THREAD

**Issue by Backyardcreators** [planetlabs-community/planet-hack-2020#89]
## BackyardCreators

_What project will this team work on?_

https://docs.google.com/presentation/d/1H5qw9ZjNy4NMuKnQ-_GjMgROp7fnYusUtoGLYMqD_9I/edit?usp=sharing

## Team Members

* R.Raman
  R.Lakshmanan
  S.O.Jeyandranath

---

(Looking for help? If so, add a `help wanted` label to this issue, then add a comment with any relevant details)

**Comment by Backyardcreators** [comment]
We need a Help To attend TheZoom Meeting

**Comment by sarasafavi** [comment]
This team has been banned.
