### ISSUE TITLE
BackyardCreators

### ISSUE THREAD

**Issue by Backyardcreators** [planetlabs-community/planet-hack-2020#90]
## (if you have a team name, it goes here)

_What project will this teamwork on?_
https://docs.google.com/presentation/d/1H5qw9ZjNy4NMuKnQ-_GjMgROp7fnYusUtoGLYMqD_9I/edit?usp=sharing

## Team Members

* R.Raman
  R.Lakshmanan
 S.o.Jeyandanath

---

(Looking for help? If so, add a `help wanted` label to this issue, then add a comment with any relevant details)

**Comment by sarasafavi** [comment]
This team has been banned.
