### ISSUE TITLE
[INTRO] 

### ISSUE THREAD

**Issue by Backyardcreators** [planetlabs-community/planet-hack-2020#91]
_Hi, my name is:_R.Raman
_my pronouns are:_

------

**What I bring to a hack team (skills, experience, interest, etc):**

**What kind of project I'd like to work on:**Phonesat and Satellite Imagery For Clean Cities

**Comment by sarasafavi** [comment]
This team has been banned.

**Comment by Backyardcreators** [comment]
Please tell us why Mam
