### ISSUE TITLE
[TEAM]Satellite Imagery for Railway Vegetation Management

### ISSUE THREAD

**Issue by smartramanlakshman** [planetlabs-community/planet-hack-2020#92]
## (if you have a team name, it goes here)

_What project will this team work on?_
Satellite Imagery for Railway Vegetation Management
(link to [PITCH] issue here)

 Team Members
R.Raman
R.Lakshmanan

* (link to [INTRO] issue(s) here)

---

(Looking for help? If so, add a `help wanted` label to this issue, then add a comment with any relevant details)

**Comment by sarasafavi** [comment]
You cannot get around a ban by using a different github account.
